name = "successor-tree-lean"
version = "0.1.0"
defaultTargets = ["SuccessorTree"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "5bd58ac291422a21f412ae354c91e7d172255a2c"

[[require]]
name = "ramsey-space-todorcevic"
git = "https://github.com/janhubicka/lean-ramsey-space-todorcevic"
rev = "54a9eb02f7f7bd2e942e95f7b44fc6f04f48892c"

[[lean_lib]]
name = "SuccessorTree"
