name = "successor-tree-lean"
version = "0.1.0"
defaultTargets = ["SuccessorTree"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "5bd58ac291422a21f412ae354c91e7d172255a2c"

[[require]]
name = "ramsey-space-todorcevic"
git = "https://github.com/janhubicka/lean-ramsey-space-todorcevic"
rev = "d0e2073ad320240f3e0c9aed5285e94eef185d45"

[[lean_lib]]
name = "SuccessorTree"
