import Mathlib

namespace SuccessorTree.BANANA

open scoped BigOperators

abbrev F2 := ZMod 2

/-- Finite data attached to a tuple in a two-sorted bilinear structure:
the linear relations on each side and all cross-pairings. -/
structure TupleInvariant (m n : ℕ) where
  leftRelations : Finset (Fin m → F2)
  rightRelations : Finset (Fin n → F2)
  pairing : Matrix (Fin m) (Fin n) F2
  deriving DecidableEq, Fintype

/-- The linear relations among a finite tuple. -/
def relationPattern {V : Type*} [AddCommGroup V] [Module F2 V]
    [DecidableEq V] {n : ℕ} (x : Fin n → V) : Finset (Fin n → F2) :=
  Finset.univ.filter fun c => (∑ i, c i • x i) = 0

/-- Extract the finite invariant used in the manuscript's
omega-categoricity argument. -/
def tupleInvariant {L R : Type*}
    [AddCommGroup L] [Module F2 L] [DecidableEq L]
    [AddCommGroup R] [Module F2 R] [DecidableEq R]
    {m n : ℕ} (β : L → R → F2)
    (x : Fin m → L) (y : Fin n → R) : TupleInvariant m n where
  leftRelations := relationPattern x
  rightRelations := relationPattern y
  pairing i j := β (x i) (y j)

/-- For each pair of tuple lengths there are only finitely many possible
linear-relation/pairing invariants.  This is the finite-data core of the
omega-categoricity proof. -/
theorem tupleInvariant_finite (m n : ℕ) :
    Finite (TupleInvariant m n) := by
  infer_instance

/-- Consequently the set of invariants realised in any bilinear structure
is finite. -/
theorem realised_tupleInvariants_finite {L R : Type*}
    [AddCommGroup L] [Module F2 L] [DecidableEq L]
    [AddCommGroup R] [Module F2 R] [DecidableEq R]
    {m n : ℕ} (β : L → R → F2) :
    Set.Finite
      (Set.range fun z : (Fin m → L) × (Fin n → R) =>
        tupleInvariant β z.1 z.2) := by
  exact Set.toFinite _


/-- The linear map whose image is the span generated by a tuple. -/
def tupleLinearMap {V : Type*} [AddCommGroup V] [Module F2 V]
    {n : ℕ} (x : Fin n → V) : (Fin n → F2) →ₗ[F2] V :=
  Fintype.linearCombination F2 x

@[simp] theorem tupleLinearMap_apply {V : Type*} [AddCommGroup V] [Module F2 V]
    {n : ℕ} (x : Fin n → V) (c : Fin n → F2) :
    tupleLinearMap x c = ∑ i, c i • x i := by
  rfl

theorem mem_relationPattern_iff {V : Type*} [AddCommGroup V] [Module F2 V]
    [DecidableEq V] {n : ℕ} (x : Fin n → V) (c : Fin n → F2) :
    c ∈ relationPattern x ↔ tupleLinearMap x c = 0 := by
  simp [relationPattern, tupleLinearMap, Fintype.linearCombination_apply]

/-- Equal relation patterns are exactly what is needed to identify the
kernels of the two coefficient maps. -/
theorem tupleLinearMap_ker_eq_of_relationPattern_eq
    {V W : Type*} [AddCommGroup V] [Module F2 V] [DecidableEq V]
    [AddCommGroup W] [Module F2 W] [DecidableEq W]
    {n : ℕ} (x : Fin n → V) (x' : Fin n → W)
    (h : relationPattern x = relationPattern x') :
    LinearMap.ker (tupleLinearMap x) = LinearMap.ker (tupleLinearMap x') := by
  ext c
  have hc := congrArg (fun s : Finset (Fin n → F2) => c ∈ s) h
  simpa [LinearMap.mem_ker, mem_relationPattern_iff] using hc

/-- Equal tuple relations canonically identify the generated linear spans.
This is the first-isomorphism-theorem step in the omega-categoricity proof. -/
noncomputable def generatedSpanEquivOfRelationPatternEq
    {V W : Type*} [AddCommGroup V] [Module F2 V] [DecidableEq V]
    [AddCommGroup W] [Module F2 W] [DecidableEq W]
    {n : ℕ} (x : Fin n → V) (x' : Fin n → W)
    (h : relationPattern x = relationPattern x') :
    LinearMap.range (tupleLinearMap x) ≃ₗ[F2]
      LinearMap.range (tupleLinearMap x') :=
  (LinearMap.quotKerEquivRange (tupleLinearMap x)).symm ≪≫ₗ
    Submodule.quotEquivOfEq _ _
      (tupleLinearMap_ker_eq_of_relationPattern_eq x x' h) ≪≫ₗ
    LinearMap.quotKerEquivRange (tupleLinearMap x')

theorem tuple_mem_generated_range
    {V : Type*} [AddCommGroup V] [Module F2 V]
    {n : ℕ} (x : Fin n → V) (i : Fin n) :
    x i ∈ LinearMap.range (tupleLinearMap x) := by
  refine ⟨Pi.single i 1, ?_⟩
  simp [tupleLinearMap]

/-- The canonical span equivalence transports the value of every coefficient
vector to the value of the same coefficient vector in the second tuple. -/
theorem generatedSpanEquivOfRelationPatternEq_apply_tupleLinearMap
    {V W : Type*} [AddCommGroup V] [Module F2 V] [DecidableEq V]
    [AddCommGroup W] [Module F2 W] [DecidableEq W]
    {n : ℕ} (x : Fin n → V) (x' : Fin n → W)
    (h : relationPattern x = relationPattern x') (c : Fin n → F2) :
    generatedSpanEquivOfRelationPatternEq x x' h
        ⟨tupleLinearMap x c, ⟨c, rfl⟩⟩ =
      ⟨tupleLinearMap x' c, ⟨c, rfl⟩⟩ := by
  let v : LinearMap.range (tupleLinearMap x) :=
    ⟨tupleLinearMap x c, ⟨c, rfl⟩⟩
  let v' : LinearMap.range (tupleLinearMap x') :=
    ⟨tupleLinearMap x' c, ⟨c, rfl⟩⟩
  change generatedSpanEquivOfRelationPatternEq x x' h v = v'
  apply Subtype.ext
  simp only [generatedSpanEquivOfRelationPatternEq, LinearEquiv.trans_apply]
  have hv :
      (tupleLinearMap x).quotKerEquivRange.symm v =
        (LinearMap.ker (tupleLinearMap x)).mkQ c :=
    LinearMap.quotKerEquivRange_symm_apply_image (f := tupleLinearMap x) c v.property
  rw [hv]
  simp only [Submodule.quotEquivOfEq_mk, LinearMap.quotKerEquivRange_apply_mk]

/-- The canonical span equivalence sends every distinguished generator to
the corresponding distinguished generator. -/
theorem generatedSpanEquivOfRelationPatternEq_apply_generator
    {V W : Type*} [AddCommGroup V] [Module F2 V] [DecidableEq V]
    [AddCommGroup W] [Module F2 W] [DecidableEq W]
    {n : ℕ} (x : Fin n → V) (x' : Fin n → W)
    (h : relationPattern x = relationPattern x') (i : Fin n) :
    generatedSpanEquivOfRelationPatternEq x x' h
        ⟨x i, tuple_mem_generated_range x i⟩ =
      ⟨x' i, tuple_mem_generated_range x' i⟩ := by
  let c : Fin n → F2 := Pi.single i 1
  calc
    generatedSpanEquivOfRelationPatternEq x x' h
        ⟨x i, tuple_mem_generated_range x i⟩ =
      generatedSpanEquivOfRelationPatternEq x x' h
        ⟨tupleLinearMap x c, ⟨c, rfl⟩⟩ := by
          congr 1
          apply Subtype.ext
          simp [c, tupleLinearMap]
    _ = ⟨tupleLinearMap x' c, ⟨c, rfl⟩⟩ :=
      generatedSpanEquivOfRelationPatternEq_apply_tupleLinearMap x x' h c
    _ = ⟨x' i, tuple_mem_generated_range x' i⟩ := by
      apply Subtype.ext
      simp [c, tupleLinearMap]

/-- The range of the coefficient map is exactly the generated span. -/
theorem tupleLinearMap_range_eq_span
    {V : Type*} [AddCommGroup V] [Module F2 V]
    {n : ℕ} (x : Fin n → V) :
    LinearMap.range (tupleLinearMap x) = Submodule.span F2 (Set.range x) := by
  simpa [tupleLinearMap] using (Fintype.range_linearCombination F2 x)

end SuccessorTree.BANANA
