import SuccessorTree.NonPrecompact.BananaStructure

/-!
# Direct sums of finite BANANA pairings

This file formalises the zero-cross-pairing direct sum used in the BANANA
circulation manuscript.  It is the algebraic core of the canonical
amalgamation over the substructure generated by the empty set.

For two finite BANANA structures `A` and `B`, their direct sum has the two
old pairing matrices on the diagonal and zero cross-pairings.  The canonical
inclusions on both sorts are BANANA embeddings.
-/

namespace SuccessorTree.NonPrecompact

open scoped Matrix

/-- Block-diagonal direct sum of two finite BANANA structures. -/
def bananaDirectSum
    {l₁ r₁ l₂ r₂ : ℕ}
    (A : BananaMatrixStructure l₁ r₁)
    (B : BananaMatrixStructure l₂ r₂) :
    BananaMatrixStructure (l₁ + l₂) (r₁ + r₂) where
  pairing := fun i j =>
    Fin.addCases
      (fun i₁ =>
        Fin.addCases
          (fun j₁ => A.pairing i₁ j₁)
          (fun _ => 0) j)
      (fun i₂ =>
        Fin.addCases
          (fun _ => 0)
          (fun j₂ => B.pairing i₂ j₂) j)
      i

namespace BananaMatrixStructure

variable {l₁ r₁ l₂ r₂ : ℕ}
variable (A : BananaMatrixStructure l₁ r₁)
variable (B : BananaMatrixStructure l₂ r₂)

/-- The block-diagonal matrix sends a vector supported on the first right
summand to a vector supported on the first left summand. -/
theorem directSum_mulVec_inl (y : Fin r₁ → F2) :
    (bananaDirectSum A B).pairing *ᵥ Fin.append y 0 =
      Fin.append (A.pairing *ᵥ y) 0 := by
  apply funext
  intro i
  induction i using Fin.addCases <;>
    simp [bananaDirectSum, Matrix.mulVec, dotProduct, Fin.sum_univ_add]

/-- The analogous statement for the second right summand. -/
theorem directSum_mulVec_inr (y : Fin r₂ → F2) :
    (bananaDirectSum A B).pairing *ᵥ Fin.append 0 y =
      Fin.append 0 (B.pairing *ᵥ y) := by
  apply funext
  intro i
  induction i using Fin.addCases <;>
    simp [bananaDirectSum, Matrix.mulVec, dotProduct, Fin.sum_univ_add]

/-- Inclusion of the first left summand. -/
def directSumLeftInl {l₁ l₂ : ℕ} :
    (Fin l₁ → F2) →ₗ[F2] (Fin (l₁ + l₂) → F2) where
  toFun x := Fin.append x 0
  map_add' x y := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp
  map_smul' c x := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp

/-- Inclusion of the first right summand. -/
def directSumRightInl {r₁ r₂ : ℕ} :
    (Fin r₁ → F2) →ₗ[F2] (Fin (r₁ + r₂) → F2) where
  toFun y := Fin.append y 0
  map_add' x y := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp
  map_smul' c x := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp

/-- Inclusion of the second left summand. -/
def directSumLeftInr {l₁ l₂ : ℕ} :
    (Fin l₂ → F2) →ₗ[F2] (Fin (l₁ + l₂) → F2) where
  toFun x := Fin.append 0 x
  map_add' x y := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp
  map_smul' c x := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp

/-- Inclusion of the second right summand. -/
def directSumRightInr {r₁ r₂ : ℕ} :
    (Fin r₂ → F2) →ₗ[F2] (Fin (r₁ + r₂) → F2) where
  toFun y := Fin.append 0 y
  map_add' x y := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp
  map_smul' c x := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp

theorem directSumLeftInl_injective {l₁ l₂ : ℕ} :
    Function.Injective (directSumLeftInl (l₁ := l₁) (l₂ := l₂)) := by
  intro x y h
  funext i
  have hi := congrFun h (Fin.castAdd l₂ i)
  simpa [directSumLeftInl] using hi

theorem directSumRightInl_injective {r₁ r₂ : ℕ} :
    Function.Injective (directSumRightInl (r₁ := r₁) (r₂ := r₂)) := by
  intro x y h
  funext i
  have hi := congrFun h (Fin.castAdd r₂ i)
  simpa [directSumRightInl] using hi

theorem directSumLeftInr_injective {l₁ l₂ : ℕ} :
    Function.Injective (directSumLeftInr (l₁ := l₁) (l₂ := l₂)) := by
  intro x y h
  funext i
  have hi := congrFun h (Fin.natAdd l₁ i)
  simpa [directSumLeftInr] using hi

theorem directSumRightInr_injective {r₁ r₂ : ℕ} :
    Function.Injective (directSumRightInr (r₁ := r₁) (r₂ := r₂)) := by
  intro x y h
  funext i
  have hi := congrFun h (Fin.natAdd r₁ i)
  simpa [directSumRightInr] using hi

theorem directSum_inl_pairing_apply
    (x : Fin l₁ → F2) (y : Fin r₁ → F2) :
    (bananaDirectSum A B).eval
        (directSumLeftInl (l₁ := l₁) (l₂ := l₂) x)
        (directSumRightInl (r₁ := r₁) (r₂ := r₂) y) =
      A.eval x y := by
  unfold eval
  rw [directSum_mulVec_inl]
  change
    (∑ i : Fin (l₁ + l₂),
      Fin.append x 0 i * Fin.append (A.pairing *ᵥ y) 0 i) =
      x ⬝ᵥ (A.pairing *ᵥ y)
  rw [Fin.sum_univ_add]
  simp [dotProduct]

theorem directSum_inr_pairing_apply
    (x : Fin l₂ → F2) (y : Fin r₂ → F2) :
    (bananaDirectSum A B).eval
        (directSumLeftInr (l₁ := l₁) (l₂ := l₂) x)
        (directSumRightInr (r₁ := r₁) (r₂ := r₂) y) =
      B.eval x y := by
  unfold eval
  rw [directSum_mulVec_inr]
  change
    (∑ i : Fin (l₁ + l₂),
      Fin.append 0 x i * Fin.append 0 (B.pairing *ᵥ y) i) =
      x ⬝ᵥ (B.pairing *ᵥ y)
  rw [Fin.sum_univ_add]
  simp [dotProduct]

/-- The first summand embeds canonically into the direct sum. -/
def directSumInlEmbedding :
    BananaMatrixEmbedding A (bananaDirectSum A B) where
  left := directSumLeftInl (l₁ := l₁) (l₂ := l₂)
  right := directSumRightInl (r₁ := r₁) (r₂ := r₂)
  left_injective := directSumLeftInl_injective
  right_injective := directSumRightInl_injective
  pairing_apply := directSum_inl_pairing_apply A B

/-- The second summand embeds canonically into the direct sum. -/
def directSumInrEmbedding :
    BananaMatrixEmbedding B (bananaDirectSum A B) where
  left := directSumLeftInr (l₁ := l₁) (l₂ := l₂)
  right := directSumRightInr (r₁ := r₁) (r₂ := r₂)
  left_injective := directSumLeftInr_injective
  right_injective := directSumRightInr_injective
  pairing_apply := directSum_inr_pairing_apply A B

/-- The two canonical summands have zero cross-pairing. -/
theorem directSum_cross_pairing_left_right
    (x : Fin l₁ → F2) (y : Fin r₂ → F2) :
    (bananaDirectSum A B).eval
        (directSumLeftInl (l₁ := l₁) (l₂ := l₂) x)
        (directSumRightInr (r₁ := r₁) (r₂ := r₂) y) = 0 := by
  unfold eval
  rw [directSum_mulVec_inr]
  change
    (∑ i : Fin (l₁ + l₂),
      Fin.append x 0 i * Fin.append 0 (B.pairing *ᵥ y) i) = 0
  rw [Fin.sum_univ_add]
  simp

/-- The other cross-pairing is zero as well. -/
theorem directSum_cross_pairing_right_left
    (x : Fin l₂ → F2) (y : Fin r₁ → F2) :
    (bananaDirectSum A B).eval
        (directSumLeftInr (l₁ := l₁) (l₂ := l₂) x)
        (directSumRightInl (r₁ := r₁) (r₂ := r₂) y) = 0 := by
  unfold eval
  rw [directSum_mulVec_inl]
  change
    (∑ i : Fin (l₁ + l₂),
      Fin.append 0 x i * Fin.append (A.pairing *ᵥ y) 0 i) = 0
  rw [Fin.sum_univ_add]
  simp

end BananaMatrixStructure

end SuccessorTree.NonPrecompact
