import SuccessorTree.NonPrecompact.BananaStructure

/-!
# Direct sums of finite BANANA pairings

This file formalises the zero-cross-pairing direct sum used in the BANANA
circulation manuscript.  It is the algebraic core of the canonical
amalgamation over the substructure generated by the empty set.

For two finite BANANA structures `A` and `B`, their direct sum has the two
old pairing matrices on the diagonal and zero cross-pairings.  The canonical
inclusions on both sorts are BANANA embeddings.
-/

namespace SuccessorTree.NonPrecompact

open scoped Matrix

/-- Block-diagonal direct sum of two finite BANANA structures. -/
def bananaDirectSum
    {l₁ r₁ l₂ r₂ : ℕ}
    (A : BananaMatrixStructure l₁ r₁)
    (B : BananaMatrixStructure l₂ r₂) :
    BananaMatrixStructure (l₁ + l₂) (r₁ + r₂) where
  pairing := fun i j =>
    Fin.addCases
      (fun i₁ =>
        Fin.addCases
          (fun j₁ => A.pairing i₁ j₁)
          (fun _ => 0) j)
      (fun i₂ =>
        Fin.addCases
          (fun _ => 0)
          (fun j₂ => B.pairing i₂ j₂) j)
      i

namespace BananaMatrixStructure

variable {l₁ r₁ l₂ r₂ : ℕ}
variable (A : BananaMatrixStructure l₁ r₁)
variable (B : BananaMatrixStructure l₂ r₂)

/-- The block-diagonal matrix sends a vector supported on the first right
summand to a vector supported on the first left summand. -/
theorem directSum_mulVec_inl (y : Fin r₁ → F2) :
    (bananaDirectSum A B).pairing *ᵥ Fin.append y 0 =
      Fin.append (A.pairing *ᵥ y) 0 := by
  apply funext
  intro i
  induction i using Fin.addCases <;>
    simp [bananaDirectSum, Matrix.mulVec, dotProduct, Fin.sum_univ_add]

/-- The analogous statement for the second right summand. -/
theorem directSum_mulVec_inr (y : Fin r₂ → F2) :
    (bananaDirectSum A B).pairing *ᵥ Fin.append 0 y =
      Fin.append 0 (B.pairing *ᵥ y) := by
  apply funext
  intro i
  induction i using Fin.addCases <;>
    simp [bananaDirectSum, Matrix.mulVec, dotProduct, Fin.sum_univ_add]

/-- Inclusion of the first left summand. -/
def directSumLeftInl {l₁ l₂ : ℕ} :
    (Fin l₁ → F2) →ₗ[F2] (Fin (l₁ + l₂) → F2) where
  toFun x := Fin.append x 0
  map_add' x y := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp
  map_smul' c x := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp

/-- Inclusion of the first right summand. -/
def directSumRightInl {r₁ r₂ : ℕ} :
    (Fin r₁ → F2) →ₗ[F2] (Fin (r₁ + r₂) → F2) where
  toFun y := Fin.append y 0
  map_add' x y := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp
  map_smul' c x := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp

/-- Inclusion of the second left summand. -/
def directSumLeftInr {l₁ l₂ : ℕ} :
    (Fin l₂ → F2) →ₗ[F2] (Fin (l₁ + l₂) → F2) where
  toFun x := Fin.append 0 x
  map_add' x y := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp
  map_smul' c x := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp

/-- Inclusion of the second right summand. -/
def directSumRightInr {r₁ r₂ : ℕ} :
    (Fin r₂ → F2) →ₗ[F2] (Fin (r₁ + r₂) → F2) where
  toFun y := Fin.append 0 y
  map_add' x y := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp
  map_smul' c x := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp

theorem directSumLeftInl_injective {l₁ l₂ : ℕ} :
    Function.Injective (directSumLeftInl (l₁ := l₁) (l₂ := l₂)) := by
  intro x y h
  funext i
  have hi := congrFun h (Fin.castAdd l₂ i)
  simpa [directSumLeftInl] using hi

theorem directSumRightInl_injective {r₁ r₂ : ℕ} :
    Function.Injective (directSumRightInl (r₁ := r₁) (r₂ := r₂)) := by
  intro x y h
  funext i
  have hi := congrFun h (Fin.castAdd r₂ i)
  simpa [directSumRightInl] using hi

theorem directSumLeftInr_injective {l₁ l₂ : ℕ} :
    Function.Injective (directSumLeftInr (l₁ := l₁) (l₂ := l₂)) := by
  intro x y h
  funext i
  have hi := congrFun h (Fin.natAdd l₁ i)
  simpa [directSumLeftInr] using hi

theorem directSumRightInr_injective {r₁ r₂ : ℕ} :
    Function.Injective (directSumRightInr (r₁ := r₁) (r₂ := r₂)) := by
  intro x y h
  funext i
  have hi := congrFun h (Fin.natAdd r₁ i)
  simpa [directSumRightInr] using hi

theorem directSum_inl_pairing_apply
    (x : Fin l₁ → F2) (y : Fin r₁ → F2) :
    (bananaDirectSum A B).eval
        (directSumLeftInl (l₁ := l₁) (l₂ := l₂) x)
        (directSumRightInl (r₁ := r₁) (r₂ := r₂) y) =
      A.eval x y := by
  unfold eval
  change
    Fin.append x 0 ⬝ᵥ
      (bananaDirectSum A B).pairing *ᵥ Fin.append y 0 =
      x ⬝ᵥ (A.pairing *ᵥ y)
  rw [directSum_mulVec_inl]
  change
    (∑ i : Fin (l₁ + l₂),
      Fin.append x 0 i * Fin.append (A.pairing *ᵥ y) 0 i) =
      x ⬝ᵥ (A.pairing *ᵥ y)
  rw [Fin.sum_univ_add]
  simp [dotProduct]

theorem directSum_inr_pairing_apply
    (x : Fin l₂ → F2) (y : Fin r₂ → F2) :
    (bananaDirectSum A B).eval
        (directSumLeftInr (l₁ := l₁) (l₂ := l₂) x)
        (directSumRightInr (r₁ := r₁) (r₂ := r₂) y) =
      B.eval x y := by
  unfold eval
  change
    Fin.append 0 x ⬝ᵥ
      (bananaDirectSum A B).pairing *ᵥ Fin.append 0 y =
      x ⬝ᵥ (B.pairing *ᵥ y)
  rw [directSum_mulVec_inr]
  change
    (∑ i : Fin (l₁ + l₂),
      Fin.append 0 x i * Fin.append 0 (B.pairing *ᵥ y) i) =
      x ⬝ᵥ (B.pairing *ᵥ y)
  rw [Fin.sum_univ_add]
  simp [dotProduct]

/-- The first summand embeds canonically into the direct sum. -/
def directSumInlEmbedding :
    BananaMatrixEmbedding A (bananaDirectSum A B) where
  left := directSumLeftInl (l₁ := l₁) (l₂ := l₂)
  right := directSumRightInl (r₁ := r₁) (r₂ := r₂)
  left_injective := directSumLeftInl_injective
  right_injective := directSumRightInl_injective
  pairing_apply := directSum_inl_pairing_apply A B

/-- The second summand embeds canonically into the direct sum. -/
def directSumInrEmbedding :
    BananaMatrixEmbedding B (bananaDirectSum A B) where
  left := directSumLeftInr (l₁ := l₁) (l₂ := l₂)
  right := directSumRightInr (r₁ := r₁) (r₂ := r₂)
  left_injective := directSumLeftInr_injective
  right_injective := directSumRightInr_injective
  pairing_apply := directSum_inr_pairing_apply A B

/-- The two canonical summands have zero cross-pairing. -/
theorem directSum_cross_pairing_left_right
    (x : Fin l₁ → F2) (y : Fin r₂ → F2) :
    (bananaDirectSum A B).eval
        (directSumLeftInl (l₁ := l₁) (l₂ := l₂) x)
        (directSumRightInr (r₁ := r₁) (r₂ := r₂) y) = 0 := by
  unfold eval
  change
    Fin.append x 0 ⬝ᵥ
      (bananaDirectSum A B).pairing *ᵥ Fin.append 0 y = 0
  rw [directSum_mulVec_inr]
  change
    (∑ i : Fin (l₁ + l₂),
      Fin.append x 0 i * Fin.append 0 (B.pairing *ᵥ y) i) = 0
  rw [Fin.sum_univ_add]
  simp

/-- The other cross-pairing is zero as well. -/
theorem directSum_cross_pairing_right_left
    (x : Fin l₂ → F2) (y : Fin r₁ → F2) :
    (bananaDirectSum A B).eval
        (directSumLeftInr (l₁ := l₁) (l₂ := l₂) x)
        (directSumRightInl (r₁ := r₁) (r₂ := r₂) y) = 0 := by
  unfold eval
  change
    Fin.append 0 x ⬝ᵥ
      (bananaDirectSum A B).pairing *ᵥ Fin.append y 0 = 0
  rw [directSum_mulVec_inl]
  change
    (∑ i : Fin (l₁ + l₂),
      Fin.append 0 x i * Fin.append (A.pairing *ᵥ y) 0 i) = 0
  rw [Fin.sum_univ_add]
  simp


/-- First coordinate block of a vector on a direct-sum coordinate space. -/
def finLeftPart {m n : ℕ} (x : Fin (m + n) → F2) : Fin m → F2 :=
  fun i => x (Fin.castAdd n i)

/-- Second coordinate block of a vector on a direct-sum coordinate space. -/
def finRightPart {m n : ℕ} (x : Fin (m + n) → F2) : Fin n → F2 :=
  fun i => x (Fin.natAdd m i)


@[simp] theorem finLeftPart_add
    {m n : ℕ} (x y : Fin (m + n) → F2) :
    finLeftPart (x + y) = finLeftPart x + finLeftPart y := by
  funext i
  rfl

@[simp] theorem finRightPart_add
    {m n : ℕ} (x y : Fin (m + n) → F2) :
    finRightPart (x + y) = finRightPart x + finRightPart y := by
  funext i
  rfl

@[simp] theorem finLeftPart_smul
    {m n : ℕ} (a : F2) (x : Fin (m + n) → F2) :
    finLeftPart (a • x) = a • finLeftPart x := by
  funext i
  rfl

@[simp] theorem finRightPart_smul
    {m n : ℕ} (a : F2) (x : Fin (m + n) → F2) :
    finRightPart (a • x) = a • finRightPart x := by
  funext i
  rfl

/-- Direct sum of two linear maps between finite coordinate spaces. -/
def directSumLinearMap
    {m₁ m₂ n₁ n₂ : ℕ}
    (f : (Fin m₁ → F2) →ₗ[F2] (Fin n₁ → F2))
    (g : (Fin m₂ → F2) →ₗ[F2] (Fin n₂ → F2)) :
    (Fin (m₁ + m₂) → F2) →ₗ[F2] (Fin (n₁ + n₂) → F2) where
  toFun x := Fin.append (f (finLeftPart x)) (g (finRightPart x))
  map_add' x y := by
    apply funext
    intro i
    induction i using Fin.addCases <;>
      simp [directSumLinearMap]
  map_smul' a x := by
    apply funext
    intro i
    induction i using Fin.addCases <;>
      simp [directSumLinearMap]

@[simp] theorem finLeftPart_directSumLinearMap
    {m₁ m₂ n₁ n₂ : ℕ}
    (f : (Fin m₁ → F2) →ₗ[F2] (Fin n₁ → F2))
    (g : (Fin m₂ → F2) →ₗ[F2] (Fin n₂ → F2))
    (x : Fin (m₁ + m₂) → F2) :
    finLeftPart (directSumLinearMap f g x) = f (finLeftPart x) := by
  funext i
  simp [finLeftPart, directSumLinearMap]

@[simp] theorem finRightPart_directSumLinearMap
    {m₁ m₂ n₁ n₂ : ℕ}
    (f : (Fin m₁ → F2) →ₗ[F2] (Fin n₁ → F2))
    (g : (Fin m₂ → F2) →ₗ[F2] (Fin n₂ → F2))
    (x : Fin (m₁ + m₂) → F2) :
    finRightPart (directSumLinearMap f g x) = g (finRightPart x) := by
  funext i
  simp [finRightPart, directSumLinearMap]

theorem directSumLinearMap_injective
    {m₁ m₂ n₁ n₂ : ℕ}
    {f : (Fin m₁ → F2) →ₗ[F2] (Fin n₁ → F2)}
    {g : (Fin m₂ → F2) →ₗ[F2] (Fin n₂ → F2)}
    (hf : Function.Injective f)
    (hg : Function.Injective g) :
    Function.Injective (directSumLinearMap f g) := by
  intro x y h
  have hleft :
      f (finLeftPart x) = f (finLeftPart y) := by
    funext i
    have hi := congrFun h (Fin.castAdd n₂ i)
    simpa [directSumLinearMap] using hi
  have hright :
      g (finRightPart x) = g (finRightPart y) := by
    funext i
    have hi := congrFun h (Fin.natAdd n₁ i)
    simpa [directSumLinearMap] using hi
  have hxleft := hf hleft
  have hxright := hg hright
  apply funext
  intro i
  induction i using Fin.addCases with
  | left i =>
      exact congrFun hxleft i
  | right i =>
      exact congrFun hxright i

/-- The block-diagonal pairing acts independently on the two coordinate
blocks. -/
theorem directSum_mulVec
    (y : Fin (r₁ + r₂) → F2) :
    (bananaDirectSum A B).pairing *ᵥ y =
      Fin.append
        (A.pairing *ᵥ finLeftPart y)
        (B.pairing *ᵥ finRightPart y) := by
  apply funext
  intro i
  induction i using Fin.addCases <;>
    simp [bananaDirectSum, Matrix.mulVec, dotProduct,
      finLeftPart, finRightPart, Fin.sum_univ_add]

/-- Evaluation of the direct-sum pairing splits into the sum of the two old
pairings. -/
theorem directSum_eval_eq
    (x : Fin (l₁ + l₂) → F2)
    (y : Fin (r₁ + r₂) → F2) :
    (bananaDirectSum A B).eval x y =
      A.eval (finLeftPart x) (finLeftPart y) +
      B.eval (finRightPart x) (finRightPart y) := by
  unfold eval
  rw [directSum_mulVec]
  change
    (∑ i : Fin (l₁ + l₂),
      x i *
        Fin.append
          (A.pairing *ᵥ finLeftPart y)
          (B.pairing *ᵥ finRightPart y) i) =
      (finLeftPart x ⬝ᵥ (A.pairing *ᵥ finLeftPart y)) +
      (finRightPart x ⬝ᵥ (B.pairing *ᵥ finRightPart y))
  rw [Fin.sum_univ_add]
  simp [dotProduct, finLeftPart, finRightPart]

/-- Direct sum of two BANANA embeddings.  This is the functorial map on
morphisms for the zero-cross-pairing direct sum. -/
def directSumEmbedding
    {l₁' r₁' l₂' r₂' : ℕ}
    {A' : BananaMatrixStructure l₁' r₁'}
    {B' : BananaMatrixStructure l₂' r₂'}
    (f : BananaMatrixEmbedding A A')
    (g : BananaMatrixEmbedding B B') :
    BananaMatrixEmbedding
      (bananaDirectSum A B)
      (bananaDirectSum A' B') where
  left := directSumLinearMap f.left g.left
  right := directSumLinearMap f.right g.right
  left_injective :=
    directSumLinearMap_injective f.left_injective g.left_injective
  right_injective :=
    directSumLinearMap_injective f.right_injective g.right_injective
  pairing_apply := by
    intro x y
    rw [directSum_eval_eq, directSum_eval_eq]
    simp only [finLeftPart_directSumLinearMap,
      finRightPart_directSumLinearMap]
    rw [f.pairing_apply, g.pairing_apply]


end BananaMatrixStructure

end SuccessorTree.NonPrecompact
