import SuccessorTree.NonPrecompact.BananaStructure

/-!
# Direct sums of finite BANANA pairings

This file formalises the zero-cross-pairing direct sum used in the BANANA
circulation manuscript.  It is the algebraic core of the canonical
amalgamation over the substructure generated by the empty set.

For two finite BANANA structures `A` and `B`, their direct sum has the two
old pairing matrices on the diagonal and zero cross-pairings.  The canonical
inclusions on both sorts are BANANA embeddings.
-/

namespace SuccessorTree.NonPrecompact

open scoped Matrix

/-- Block-diagonal direct sum of two finite BANANA structures. -/
def bananaDirectSum
    {l₁ r₁ l₂ r₂ : ℕ}
    (A : BananaMatrixStructure l₁ r₁)
    (B : BananaMatrixStructure l₂ r₂) :
    BananaMatrixStructure (l₁ + l₂) (r₁ + r₂) where
  pairing := fun i j =>
    Fin.addCases
      (fun i₁ =>
        Fin.addCases
          (fun j₁ => A.pairing i₁ j₁)
          (fun _ => 0) j)
      (fun i₂ =>
        Fin.addCases
          (fun _ => 0)
          (fun j₂ => B.pairing i₂ j₂) j)
      i

namespace BananaMatrixStructure

variable {l₁ r₁ l₂ r₂ : ℕ}
variable (A : BananaMatrixStructure l₁ r₁)
variable (B : BananaMatrixStructure l₂ r₂)

/-- The block-diagonal matrix sends a vector supported on the first right
summand to a vector supported on the first left summand. -/
theorem directSum_mulVec_inl (y : Fin r₁ → F2) :
    (bananaDirectSum A B).pairing *ᵥ Fin.append y 0 =
      Fin.append (A.pairing *ᵥ y) 0 := by
  apply funext
  intro i
  induction i using Fin.addCases <;>
    simp [bananaDirectSum, Matrix.mulVec, dotProduct, Fin.sum_univ_add]

/-- The analogous statement for the second right summand. -/
theorem directSum_mulVec_inr (y : Fin r₂ → F2) :
    (bananaDirectSum A B).pairing *ᵥ Fin.append 0 y =
      Fin.append 0 (B.pairing *ᵥ y) := by
  apply funext
  intro i
  induction i using Fin.addCases <;>
    simp [bananaDirectSum, Matrix.mulVec, dotProduct, Fin.sum_univ_add]

/-- Inclusion of the first left summand. -/
def directSumLeftInl {l₁ l₂ : ℕ} :
    (Fin l₁ → F2) →ₗ[F2] (Fin (l₁ + l₂) → F2) where
  toFun x := Fin.append x 0
  map_add' x y := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp
  map_smul' c x := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp

/-- Inclusion of the first right summand. -/
def directSumRightInl {r₁ r₂ : ℕ} :
    (Fin r₁ → F2) →ₗ[F2] (Fin (r₁ + r₂) → F2) where
  toFun y := Fin.append y 0
  map_add' x y := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp
  map_smul' c x := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp

/-- Inclusion of the second left summand. -/
def directSumLeftInr {l₁ l₂ : ℕ} :
    (Fin l₂ → F2) →ₗ[F2] (Fin (l₁ + l₂) → F2) where
  toFun x := Fin.append 0 x
  map_add' x y := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp
  map_smul' c x := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp

/-- Inclusion of the second right summand. -/
def directSumRightInr {r₁ r₂ : ℕ} :
    (Fin r₂ → F2) →ₗ[F2] (Fin (r₁ + r₂) → F2) where
  toFun y := Fin.append 0 y
  map_add' x y := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp
  map_smul' c x := by
    apply funext
    rw [Fin.forall_fin_add]
    constructor <;> intro i <;> simp

theorem directSumLeftInl_injective {l₁ l₂ : ℕ} :
    Function.Injective (directSumLeftInl (l₁ := l₁) (l₂ := l₂)) := by
  intro x y h
  funext i
  have hi := congrFun h (Fin.castAdd l₂ i)
  simpa [directSumLeftInl] using hi

theorem directSumRightInl_injective {r₁ r₂ : ℕ} :
    Function.Injective (directSumRightInl (r₁ := r₁) (r₂ := r₂)) := by
  intro x y h
  funext i
  have hi := congrFun h (Fin.castAdd r₂ i)
  simpa [directSumRightInl] using hi

theorem directSumLeftInr_injective {l₁ l₂ : ℕ} :
    Function.Injective (directSumLeftInr (l₁ := l₁) (l₂ := l₂)) := by
  intro x y h
  funext i
  have hi := congrFun h (Fin.natAdd l₁ i)
  simpa [directSumLeftInr] using hi

theorem directSumRightInr_injective {r₁ r₂ : ℕ} :
    Function.Injective (directSumRightInr (r₁ := r₁) (r₂ := r₂)) := by
  intro x y h
  funext i
  have hi := congrFun h (Fin.natAdd r₁ i)
  simpa [directSumRightInr] using hi

theorem directSum_inl_pairing_apply
    (x : Fin l₁ → F2) (y : Fin r₁ → F2) :
    (bananaDirectSum A B).eval
        (directSumLeftInl (l₁ := l₁) (l₂ := l₂) x)
        (directSumRightInl (r₁ := r₁) (r₂ := r₂) y) =
      A.eval x y := by
  unfold eval
  change
    Fin.append x 0 ⬝ᵥ
      (bananaDirectSum A B).pairing *ᵥ Fin.append y 0 =
      x ⬝ᵥ (A.pairing *ᵥ y)
  rw [directSum_mulVec_inl]
  change
    (∑ i : Fin (l₁ + l₂),
      Fin.append x 0 i * Fin.append (A.pairing *ᵥ y) 0 i) =
      x ⬝ᵥ (A.pairing *ᵥ y)
  rw [Fin.sum_univ_add]
  simp [dotProduct]

theorem directSum_inr_pairing_apply
    (x : Fin l₂ → F2) (y : Fin r₂ → F2) :
    (bananaDirectSum A B).eval
        (directSumLeftInr (l₁ := l₁) (l₂ := l₂) x)
        (directSumRightInr (r₁ := r₁) (r₂ := r₂) y) =
      B.eval x y := by
  unfold eval
  change
    Fin.append 0 x ⬝ᵥ
      (bananaDirectSum A B).pairing *ᵥ Fin.append 0 y =
      x ⬝ᵥ (B.pairing *ᵥ y)
  rw [directSum_mulVec_inr]
  change
    (∑ i : Fin (l₁ + l₂),
      Fin.append 0 x i * Fin.append 0 (B.pairing *ᵥ y) i) =
      x ⬝ᵥ (B.pairing *ᵥ y)
  rw [Fin.sum_univ_add]
  simp [dotProduct]

/-- The first summand embeds canonically into the direct sum. -/
def directSumInlEmbedding :
    BananaMatrixEmbedding A (bananaDirectSum A B) where
  left := directSumLeftInl (l₁ := l₁) (l₂ := l₂)
  right := directSumRightInl (r₁ := r₁) (r₂ := r₂)
  left_injective := directSumLeftInl_injective
  right_injective := directSumRightInl_injective
  pairing_apply := directSum_inl_pairing_apply A B

/-- The second summand embeds canonically into the direct sum. -/
def directSumInrEmbedding :
    BananaMatrixEmbedding B (bananaDirectSum A B) where
  left := directSumLeftInr (l₁ := l₁) (l₂ := l₂)
  right := directSumRightInr (r₁ := r₁) (r₂ := r₂)
  left_injective := directSumLeftInr_injective
  right_injective := directSumRightInr_injective
  pairing_apply := directSum_inr_pairing_apply A B

/-- The two canonical summands have zero cross-pairing. -/
theorem directSum_cross_pairing_left_right
    (x : Fin l₁ → F2) (y : Fin r₂ → F2) :
    (bananaDirectSum A B).eval
        (directSumLeftInl (l₁ := l₁) (l₂ := l₂) x)
        (directSumRightInr (r₁ := r₁) (r₂ := r₂) y) = 0 := by
  unfold eval
  change
    Fin.append x 0 ⬝ᵥ
      (bananaDirectSum A B).pairing *ᵥ Fin.append 0 y = 0
  rw [directSum_mulVec_inr]
  change
    (∑ i : Fin (l₁ + l₂),
      Fin.append x 0 i * Fin.append 0 (B.pairing *ᵥ y) i) = 0
  rw [Fin.sum_univ_add]
  simp

/-- The other cross-pairing is zero as well. -/
theorem directSum_cross_pairing_right_left
    (x : Fin l₂ → F2) (y : Fin r₁ → F2) :
    (bananaDirectSum A B).eval
        (directSumLeftInr (l₁ := l₁) (l₂ := l₂) x)
        (directSumRightInl (r₁ := r₁) (r₂ := r₂) y) = 0 := by
  unfold eval
  change
    Fin.append 0 x ⬝ᵥ
      (bananaDirectSum A B).pairing *ᵥ Fin.append y 0 = 0
  rw [directSum_mulVec_inl]
  change
    (∑ i : Fin (l₁ + l₂),
      Fin.append 0 x i * Fin.append (A.pairing *ᵥ y) 0 i) = 0
  rw [Fin.sum_univ_add]
  simp


/-- Restrict a vector on a sum of coordinate blocks to the first block. -/
def directSumLeftPart {m n : ℕ} (x : Fin (m + n) → F2) : Fin m → F2 :=
  fun i => x (Fin.castAdd n i)

/-- Restrict a vector on a sum of coordinate blocks to the second block. -/
def directSumRightPart {m n : ℕ} (x : Fin (m + n) → F2) : Fin n → F2 :=
  fun i => x (Fin.natAdd m i)

@[simp] theorem directSumLeftPart_add {m n : ℕ}
    (x y : Fin (m + n) → F2) :
    directSumLeftPart (x + y) =
      directSumLeftPart x + directSumLeftPart y := by
  funext i
  simp [directSumLeftPart]

@[simp] theorem directSumRightPart_add {m n : ℕ}
    (x y : Fin (m + n) → F2) :
    directSumRightPart (x + y) =
      directSumRightPart x + directSumRightPart y := by
  funext i
  simp [directSumRightPart]

@[simp] theorem directSumLeftPart_smul {m n : ℕ}
    (a : F2) (x : Fin (m + n) → F2) :
    directSumLeftPart (a • x) =
      a • directSumLeftPart x := by
  funext i
  simp [directSumLeftPart]

@[simp] theorem directSumRightPart_smul {m n : ℕ}
    (a : F2) (x : Fin (m + n) → F2) :
    directSumRightPart (a • x) =
      a • directSumRightPart x := by
  funext i
  simp [directSumRightPart]

theorem append_directSumParts {m n : ℕ} (x : Fin (m + n) → F2) :
    Fin.append (directSumLeftPart x) (directSumRightPart x) = x := by
  funext i
  induction i using Fin.addCases <;>
    simp [directSumLeftPart, directSumRightPart]

/-- Block sum of two linear maps between finite coordinate spaces. -/
def directSumLinearMap
    {m n m' n' : ℕ}
    (f : (Fin m → F2) →ₗ[F2] (Fin m' → F2))
    (g : (Fin n → F2) →ₗ[F2] (Fin n' → F2)) :
    (Fin (m + n) → F2) →ₗ[F2] (Fin (m' + n') → F2) where
  toFun x :=
    Fin.append
      (f (directSumLeftPart x))
      (g (directSumRightPart x))
  map_add' x y := by
    apply funext
    intro i
    induction i using Fin.addCases <;>
      simp [directSumLinearMap]
  map_smul' a x := by
    apply funext
    intro i
    induction i using Fin.addCases <;>
      simp [directSumLinearMap]

theorem directSumLinearMap_injective
    {m n m' n' : ℕ}
    {f : (Fin m → F2) →ₗ[F2] (Fin m' → F2)}
    {g : (Fin n → F2) →ₗ[F2] (Fin n' → F2)}
    (hf : Function.Injective f)
    (hg : Function.Injective g) :
    Function.Injective (directSumLinearMap f g) := by
  intro x y h
  have hleftMap :
      f (directSumLeftPart x) = f (directSumLeftPart y) := by
    funext i
    have hi := congrFun h (Fin.castAdd n' i)
    simpa [directSumLinearMap] using hi
  have hrightMap :
      g (directSumRightPart x) = g (directSumRightPart y) := by
    funext i
    have hi := congrFun h (Fin.natAdd m' i)
    simpa [directSumLinearMap] using hi
  have hleft :
      directSumLeftPart x = directSumLeftPart y :=
    hf hleftMap
  have hright :
      directSumRightPart x = directSumRightPart y :=
    hg hrightMap
  calc
    x = Fin.append (directSumLeftPart x) (directSumRightPart x) :=
      (append_directSumParts x).symm
    _ = Fin.append (directSumLeftPart y) (directSumRightPart y) := by
      rw [hleft, hright]
    _ = y := append_directSumParts y

/-- Evaluation of a direct-sum pairing splits as the sum of the two old
pairings. -/
theorem directSum_eval_append
    (x₁ : Fin l₁ → F2) (x₂ : Fin l₂ → F2)
    (y₁ : Fin r₁ → F2) (y₂ : Fin r₂ → F2) :
    (bananaDirectSum A B).eval
        (Fin.append x₁ x₂) (Fin.append y₁ y₂) =
      A.eval x₁ y₁ + B.eval x₂ y₂ := by
  unfold eval
  have hmul :
      (bananaDirectSum A B).pairing *ᵥ Fin.append y₁ y₂ =
        Fin.append (A.pairing *ᵥ y₁) (B.pairing *ᵥ y₂) := by
    apply funext
    intro i
    induction i using Fin.addCases <;>
      simp [bananaDirectSum, Matrix.mulVec, dotProduct, Fin.sum_univ_add]
  rw [hmul]
  change
    (∑ i : Fin (l₁ + l₂),
      Fin.append x₁ x₂ i *
        Fin.append (A.pairing *ᵥ y₁) (B.pairing *ᵥ y₂) i) =
      x₁ ⬝ᵥ (A.pairing *ᵥ y₁) +
        x₂ ⬝ᵥ (B.pairing *ᵥ y₂)
  rw [Fin.sum_univ_add]
  simp [dotProduct]

end BananaMatrixStructure

namespace BananaMatrixEmbedding

variable
  {l₁ r₁ l₂ r₂ l₁' r₁' l₂' r₂' : ℕ}
  {A₁ : BananaMatrixStructure l₁ r₁}
  {A₂ : BananaMatrixStructure l₂ r₂}
  {B₁ : BananaMatrixStructure l₁' r₁'}
  {B₂ : BananaMatrixStructure l₂' r₂'}

/-- Direct sum of two BANANA embeddings.  It acts blockwise on both vector
sorts, so embeddings on either factor extend by the identity on the other
factor by taking the other embedding to be an identity map. -/
def directSum
    (f : BananaMatrixEmbedding A₁ B₁)
    (g : BananaMatrixEmbedding A₂ B₂) :
    BananaMatrixEmbedding
      (bananaDirectSum A₁ A₂)
      (bananaDirectSum B₁ B₂) where
  left := BananaMatrixStructure.directSumLinearMap f.left g.left
  right := BananaMatrixStructure.directSumLinearMap f.right g.right
  left_injective :=
    BananaMatrixStructure.directSumLinearMap_injective
      f.left_injective g.left_injective
  right_injective :=
    BananaMatrixStructure.directSumLinearMap_injective
      f.right_injective g.right_injective
  pairing_apply := by
    intro x y
    let x₁ := BananaMatrixStructure.directSumLeftPart
      (m := l₁) (n := l₂) x
    let x₂ := BananaMatrixStructure.directSumRightPart
      (m := l₁) (n := l₂) x
    let y₁ := BananaMatrixStructure.directSumLeftPart
      (m := r₁) (n := r₂) y
    let y₂ := BananaMatrixStructure.directSumRightPart
      (m := r₁) (n := r₂) y
    have hx :
        Fin.append x₁ x₂ = x := by
      exact BananaMatrixStructure.append_directSumParts x
    have hy :
        Fin.append y₁ y₂ = y := by
      exact BananaMatrixStructure.append_directSumParts y
    change
      (bananaDirectSum B₁ B₂).eval
        (Fin.append (f.left x₁) (g.left x₂))
        (Fin.append (f.right y₁) (g.right y₂)) =
      (bananaDirectSum A₁ A₂).eval x y
    calc
      (bananaDirectSum B₁ B₂).eval
          (Fin.append (f.left x₁) (g.left x₂))
          (Fin.append (f.right y₁) (g.right y₂)) =
          B₁.eval (f.left x₁) (f.right y₁) +
            B₂.eval (g.left x₂) (g.right y₂) :=
        BananaMatrixStructure.directSum_eval_append
          B₁ B₂ (f.left x₁) (g.left x₂) (f.right y₁) (g.right y₂)
      _ = A₁.eval x₁ y₁ + A₂.eval x₂ y₂ := by
        rw [f.pairing_apply, g.pairing_apply]
      _ = (bananaDirectSum A₁ A₂).eval
          (Fin.append x₁ x₂) (Fin.append y₁ y₂) :=
        (BananaMatrixStructure.directSum_eval_append
          A₁ A₂ x₁ x₂ y₁ y₂).symm
      _ = (bananaDirectSum A₁ A₂).eval x y := by
        rw [hx, hy]

end BananaMatrixEmbedding

end SuccessorTree.NonPrecompact
