import SuccessorTree.NonPrecompact.PerfectCopy

/-!
# Coordinate BANANA structures and embeddings

This file packages the finite two-sorted bilinear structures used in the
BANANA manuscript.  The two sorts are coordinate vector spaces over `F₂`;
a structure is given by the matrix of its cross-pairing, and an embedding is
a pair of injective linear maps preserving that pairing.

The main bridge shows that `PerfectCopyMatrices` really is the matrix
presentation of an embedding between the standard perfect pairings.
-/

namespace SuccessorTree.NonPrecompact

open scoped Matrix

/-- A finite coordinate presentation of a BANANA structure:
two finite-dimensional `F₂` vector spaces and a bilinear cross-pairing. -/
structure CoordinateBanana (l r : ℕ) where
  pairingMatrix : Matrix (Fin l) (Fin r) F2

namespace CoordinateBanana

variable {l r l' r' l'' r'' : ℕ}

/-- Evaluation of the cross-pairing. -/
noncomputable def pair (A : CoordinateBanana l r)
    (x : Fin l → F2) (y : Fin r → F2) : F2 :=
  x ⬝ᵥ (A.pairingMatrix *ᵥ y)

/-- The standard perfect pairing `B_d`. -/
def perfect (d : ℕ) : CoordinateBanana d d where
  pairingMatrix := 1

@[simp] theorem perfect_pair (d : ℕ)
    (x y : Fin d → F2) :
    (perfect d).pair x y = x ⬝ᵥ y := by
  simp [pair, perfect]

/-- The rigid one-dimensional line pair `A_b`. -/
def linePair (b : F2) : CoordinateBanana 1 1 where
  pairingMatrix := fun _ _ => b

@[simp] theorem linePair_pair (b : F2)
    (a c : Fin 1 → F2) :
    (linePair b).pair a c = a 0 * b * c 0 := by
  simp [pair, linePair, Matrix.mulVec, dotProduct, mul_assoc]

/-- The distinguished nonzero generator of the one-dimensional sort. -/
def lineGenerator : Fin 1 → F2 := fun _ => 1

theorem lineGenerator_ne_zero : lineGenerator ≠ 0 := by
  intro h
  have h0 := congrFun h (0 : Fin 1)
  norm_num [lineGenerator] at h0

/-- The linear map from a one-dimensional coordinate space generated by
a vector `x`. -/
def lineMap {d : ℕ} (x : Fin d → F2) :
    (Fin 1 → F2) →ₗ[F2] (Fin d → F2) :=
  (LinearMap.toSpanSingleton F2 (Fin d → F2) x).comp
    (LinearEquiv.funUnique (Fin 1) F2 F2).toLinearMap

@[simp] theorem lineMap_apply {d : ℕ} (x : Fin d → F2)
    (a : Fin 1 → F2) :
    lineMap x a = a 0 • x := by
  simp [lineMap, LinearMap.toSpanSingleton_apply,
    LinearEquiv.funUnique_apply]

@[simp] theorem lineMap_generator {d : ℕ} (x : Fin d → F2) :
    lineMap x lineGenerator = x := by
  simp [lineGenerator]

theorem lineMap_injective {d : ℕ} {x : Fin d → F2} (hx : x ≠ 0) :
    Function.Injective (lineMap x) := by
  exact
    (LinearMap.ker_eq_bot.mp (LinearMap.ker_toSpanSingleton F2 hx)).comp
      (LinearEquiv.funUnique (Fin 1) F2 F2).injective

/-- An embedding of finite BANANA structures is a pair of injective linear
maps, one on each sort, preserving the cross-pairing. -/
structure Embedding
    (A : CoordinateBanana l r) (B : CoordinateBanana l' r') where
  left : (Fin l → F2) →ₗ[F2] (Fin l' → F2)
  right : (Fin r → F2) →ₗ[F2] (Fin r' → F2)
  left_injective : Function.Injective left
  right_injective : Function.Injective right
  pairing_apply :
    ∀ x y, B.pair (left x) (right y) = A.pair x y

namespace Embedding

variable {A : CoordinateBanana l r}
  {B : CoordinateBanana l' r'}
  {C : CoordinateBanana l'' r''}

/-- Identity embedding. -/
def refl (A : CoordinateBanana l r) : Embedding A A where
  left := LinearMap.id
  right := LinearMap.id
  left_injective := Function.injective_id
  right_injective := Function.injective_id
  pairing_apply := by simp

/-- Composition of BANANA embeddings. -/
def comp (g : Embedding B C) (f : Embedding A B) : Embedding A C where
  left := g.left.comp f.left
  right := g.right.comp f.right
  left_injective := g.left_injective.comp f.left_injective
  right_injective := g.right_injective.comp f.right_injective
  pairing_apply := by
    intro x y
    rw [LinearMap.comp_apply, LinearMap.comp_apply,
      g.pairing_apply, f.pairing_apply]

@[simp] theorem refl_left_apply (A : CoordinateBanana l r)
    (x : Fin l → F2) :
    (refl A).left x = x := rfl

@[simp] theorem refl_right_apply (A : CoordinateBanana l r)
    (y : Fin r → F2) :
    (refl A).right y = y := rfl

@[simp] theorem comp_left_apply
    (g : Embedding B C) (f : Embedding A B)
    (x : Fin l → F2) :
    (g.comp f).left x = g.left (f.left x) := rfl

@[simp] theorem comp_right_apply
    (g : Embedding B C) (f : Embedding A B)
    (y : Fin r → F2) :
    (g.comp f).right y = g.right (f.right y) := rfl

/-- The line pair generated by nonzero vectors `x,y` with pairing `b`
embeds in the standard perfect pairing. -/
def linePairEmbedding
    {d : ℕ} (b : F2) (x y : Fin d → F2)
    (hx : x ≠ 0) (hy : y ≠ 0) (hxy : x ⬝ᵥ y = b) :
    Embedding (linePair b) (perfect d) where
  left := lineMap x
  right := lineMap y
  left_injective := lineMap_injective hx
  right_injective := lineMap_injective hy
  pairing_apply := by
    intro a c
    calc
      (perfect d).pair (lineMap x a) (lineMap y c) =
          (a 0 • x) ⬝ᵥ (c 0 • y) := by simp
      _ = a 0 * (x ⬝ᵥ y) * c 0 := by
        simp [smul_eq_mul]
        ac_rfl
      _ = a 0 * b * c 0 := by rw [hxy]
      _ = (linePair b).pair a c := (linePair_pair b a c).symm

/-- The proxy predicate used by the residue-count layer yields a genuine
embedding of the rigid line-pair source, with the chosen vectors as the
images of its generators. -/
theorem exists_linePairEmbedding_of_isLinePair
    {d : ℕ} {b : F2} {x y : Fin d → F2}
    (h : PerfectCopyMatrices.IsLinePair b x y) :
    ∃ e : Embedding (linePair b) (perfect d),
      e.left lineGenerator = x ∧ e.right lineGenerator = y := by
  let e := linePairEmbedding b x y h.1 h.2.1 h.2.2
  exact ⟨e,
    by simp [e, linePairEmbedding, lineGenerator],
    by simp [e, linePairEmbedding, lineGenerator]⟩

/-- Conversely, the images of the distinguished generators under a
line-pair embedding satisfy exactly the existing `IsLinePair` predicate. -/
theorem isLinePair_generator_images
    {d : ℕ} {b : F2}
    (e : Embedding (linePair b) (perfect d)) :
    PerfectCopyMatrices.IsLinePair b
      (e.left lineGenerator) (e.right lineGenerator) := by
  have hx : e.left lineGenerator ≠ 0 := by
    intro hzero
    apply lineGenerator_ne_zero
    apply e.left_injective
    simpa using hzero
  have hy : e.right lineGenerator ≠ 0 := by
    intro hzero
    apply lineGenerator_ne_zero
    apply e.right_injective
    simpa using hzero
  have hp := e.pairing_apply lineGenerator lineGenerator
  have hpair :
      e.left lineGenerator ⬝ᵥ e.right lineGenerator = b := by
    simpa [lineGenerator] using hp
  exact ⟨hx, hy, hpair⟩

end Embedding

end CoordinateBanana

namespace PerfectCopyMatrices

variable {d n : ℕ} (E : PerfectCopyMatrices d n)

/-- A perfect-copy matrix pair is exactly a coordinate embedding
`B_d ↪ B_n` of the standard perfect BANANA structures. -/
def toBananaEmbedding :
    CoordinateBanana.Embedding
      (CoordinateBanana.perfect d)
      (CoordinateBanana.perfect n) where
  left := E.leftMap
  right := E.rightMap
  left_injective := E.leftMap_injective
  right_injective := E.rightMap_injective
  pairing_apply := by
    intro x y
    simpa using E.pairing_apply x y

@[simp] theorem toBananaEmbedding_left_apply (x : Fin d → F2) :
    E.toBananaEmbedding.left x = E.leftMap x := rfl

@[simp] theorem toBananaEmbedding_right_apply (y : Fin d → F2) :
    E.toBananaEmbedding.right y = E.rightMap y := rfl

end PerfectCopyMatrices

end SuccessorTree.NonPrecompact
