import Mathlib
import SuccessorTree.NonPrecompact.QuadraticGauss

/-!
# Codimension-two symplectic slices over F₂

This file formalises the linear-algebra step compressed in the BANANA
circulation manuscript as

  B = W ⟂ H

with H a hyperbolic plane.  We phrase only what the later colouring proof
needs: in a positive-dimensional finite nondegenerate alternating F₂-space,
there is a nonzero vector w outside a codimension-two subspace W such that
the restriction of the form to W is again nondegenerate.
-/

namespace SuccessorTree.NonPrecompact

open Module Submodule

/-- The two-coordinate linear map generated by a pair of vectors. -/
def hyperbolicPairMap
    {V : Type*} [AddCommGroup V] [Module F2 V]
    (e f : V) :
    (Fin 2 → F2) →ₗ[F2] V where
  toFun a := a 0 • e + a 1 • f
  map_add' x y := by
    simp [add_smul, add_assoc, add_left_comm, add_comm]
  map_smul' a x := by
    simp [smul_add, mul_smul, mul_comm]

@[simp] theorem hyperbolicPairMap_apply
    {V : Type*} [AddCommGroup V] [Module F2 V]
    (e f : V) (a : Fin 2 → F2) :
    hyperbolicPairMap e f a = a 0 • e + a 1 • f := rfl

/-- A pair with alternating pairing one is linearly independent. -/
theorem hyperbolicPairMap_injective
    {V : Type*} [AddCommGroup V] [Module F2 V]
    (B : LinearMap.BilinForm F2 V)
    (hAlt : B.IsAlt)
    {e f : V}
    (hef : B e f = 1) :
    Function.Injective (hyperbolicPairMap e f) := by
  have hfe : B f e = 1 := by
    simpa [hef] using (hAlt.neg_eq e f).symm
  intro x y hxy
  have h0 := congrArg (fun v => B f v) hxy
  have h1 := congrArg (fun v => B e v) hxy
  have hx0 : x 0 = y 0 := by
    simpa [hyperbolicPairMap, hAlt e, hAlt f, hef, hfe] using h0
  have hx1 : x 1 = y 1 := by
    simpa [hyperbolicPairMap, hAlt e, hAlt f, hef, hfe] using h1
  funext i
  fin_cases i
  · exact hx0
  · exact hx1

/-- The range generated by a hyperbolic pair has dimension two. -/
theorem finrank_hyperbolicPairRange
    {V : Type*} [AddCommGroup V] [Module F2 V]
    [FiniteDimensional F2 V]
    (B : LinearMap.BilinForm F2 V)
    (hAlt : B.IsAlt)
    {e f : V}
    (hef : B e f = 1) :
    finrank F2 (LinearMap.range (hyperbolicPairMap e f)) = 2 := by
  let L := hyperbolicPairMap e f
  have hker : LinearMap.ker L = ⊥ := by
    exact LinearMap.ker_eq_bot.mpr
      (hyperbolicPairMap_injective B hAlt hef)
  have hrank := L.finrank_range_add_finrank_ker
  rw [hker, finrank_bot, add_zero] at hrank
  have hdom : finrank F2 (Fin 2 → F2) = 2 := by
    simp [Module.finrank_fintype_fun_eq_card]
  exact hrank.trans hdom

/-- The form restricted to the span of a hyperbolic pair is nondegenerate. -/
theorem hyperbolicPair_restrict_nondegenerate
    {V : Type*} [AddCommGroup V] [Module F2 V]
    [FiniteDimensional F2 V]
    (B : LinearMap.BilinForm F2 V)
    (hAlt : B.IsAlt)
    {e f : V}
    (hef : B e f = 1) :
    (B.restrict (LinearMap.range (hyperbolicPairMap e f))).Nondegenerate := by
  let H := LinearMap.range (hyperbolicPairMap e f)
  change (B.restrict H).Nondegenerate
  apply LinearMap.BilinForm.Nondegenerate.ofSeparatingLeft
  intro x hx
  obtain ⟨a, ha⟩ := x.property

  have hfe : B f e = 1 := by
    simpa [hef] using (hAlt.neg_eq e f).symm

  have heH : e ∈ H := by
    refine ⟨![1, 0], ?_⟩
    simp [H, hyperbolicPairMap]
  have hfH : f ∈ H := by
    refine ⟨![0, 1], ?_⟩
    simp [H, hyperbolicPairMap]

  have hxe := hx ⟨e, heH⟩
  have hxf := hx ⟨f, hfH⟩
  change B x.val e = 0 at hxe
  change B x.val f = 0 at hxf
  rw [← ha] at hxe hxf

  have ha1 : a 1 = 0 := by
    simpa [hyperbolicPairMap, hAlt e, hAlt f, hef, hfe] using hxe
  have ha0 : a 0 = 0 := by
    simpa [hyperbolicPairMap, hAlt e, hAlt f, hef, hfe] using hxf

  apply Subtype.ext
  change x.val = 0
  rw [← ha]
  simp [hyperbolicPairMap, ha0, ha1]

/-- In a positive-dimensional finite nondegenerate alternating F₂-space,
there is a nonzero affine translate of a codimension-two nondegenerate
subspace which does not contain zero.

The returned vector is one vector of a hyperbolic pair and the returned
subspace is the orthogonal complement of their span. -/
theorem exists_nondegenerate_codimTwo_slice
    {V : Type*} [AddCommGroup V] [Module F2 V]
    [FiniteDimensional F2 V]
    (B : LinearMap.BilinForm F2 V)
    (hAlt : B.IsAlt)
    (hB : B.Nondegenerate)
    (hpos : 0 < finrank F2 V) :
    ∃ w : V, ∃ W : Submodule F2 V,
      w ≠ 0 ∧
      w ∉ W ∧
      (B.restrict W).Nondegenerate ∧
      finrank F2 W = finrank F2 V - 2 := by
  obtain ⟨e, he⟩ :=
    (Module.finrank_pos_iff_exists_ne_zero (R := F2)).mp hpos

  have hex : ∃ f : V, B e f ≠ 0 := by
    by_contra h
    push_neg at h
    exact he (hB.1 e h)

  obtain ⟨f, hef0⟩ := hex
  have hef : B e f = 1 := by
    rcases f2_eq_zero_or_one (B e f) with h0 | h1
    · exact (hef0 h0).elim
    · exact h1

  let H : Submodule F2 V :=
    LinearMap.range (hyperbolicPairMap e f)
  let W : Submodule F2 V := B.orthogonal H

  have hHnd : (B.restrict H).Nondegenerate := by
    simpa [H] using
      hyperbolicPair_restrict_nondegenerate B hAlt hef

  have hcompl : IsCompl H W := by
    dsimp [W]
    exact B.isCompl_orthogonal_of_restrict_nondegenerate
      hAlt.isRefl hHnd

  have hWnondeg : (B.restrict W).Nondegenerate := by
    rw [B.restrict_nondegenerate_iff_isCompl_orthogonal hAlt.isRefl]
    have hoo : B.orthogonal W = H := by
      dsimp [W]
      exact B.orthogonal_orthogonal hB hAlt.isRefl H
    rw [hoo]
    exact hcompl.symm

  have hHrank : finrank F2 H = 2 := by
    simpa [H] using finrank_hyperbolicPairRange B hAlt hef

  have hWrank : finrank F2 W = finrank F2 V - 2 := by
    dsimp [W]
    rw [B.finrank_orthogonal hB H, hHrank]

  have heH : e ∈ H := by
    refine ⟨![1, 0], ?_⟩
    simp [H, hyperbolicPairMap]

  have heW : e ∉ W := by
    intro hmem
    have hboth : e ∈ H ⊓ W := ⟨heH, hmem⟩
    rw [hcompl.inf_eq_bot] at hboth
    simpa using he hboth

  exact ⟨e, W, he, heW, hWnondeg, hWrank⟩

end SuccessorTree.NonPrecompact
