import SuccessorTree.V10.OriginalPoolEnvelope
import Mathlib.Tactic

/-!
# Quadratic finite budget for levels generated by meets

The v10 manuscript's upper-bound proof uses the sharp fact that the
meet-closure of N vertices of a forest has at most 2N vertices. For the
mere finiteness of big Ramsey degrees, the quadratic estimate
N + N² is sufficient. It follows immediately from the proved
original-pool meet provenance, avoiding a separate branching-count lemma.

This file bounds only original *levels* and nontrivial *meet levels*.
It does not assert that all levels selected by Algorithm 5.4 are of these
two kinds: the paper must separately classify the I1/I2/I3 selections.
The universal closure of Section 5 is used in the last theorem, rather
than any unproved equality with a finitely generated closure.
-/

namespace SuccessorTree.V10

universe u v
variable {T : Type u} [PartialOrder T] [LevelTree T]
variable {Label : Type v}

/-- A deliberately generous finite set of all original levels and the
meet levels of all ordered pairs from a finite original pool. Pairs
in different root components need not have meaningful meets; including
their values only enlarges this finite upper budget. -/
noncomputable def poolMeetLevelBudget (V : Finset T) : Finset Nat := by
  classical
  exact
    V.image LevelTree.lev ∪
      (V.product V).image (fun p : T × T =>
        LevelTree.lev (LevelTree.meet p.1 p.2))

/-- N original vertices contribute at most N+N² possible original/meet
levels. No binary branching, pruning, or monoid axioms are needed. -/
theorem poolMeetLevelBudget_card_le (V : Finset T) :
    (poolMeetLevelBudget V).card ≤ V.card + V.card ^ 2 := by
  classical
  unfold poolMeetLevelBudget
  calc
    (V.image LevelTree.lev ∪
      (V.product V).image (fun p : T × T =>
        LevelTree.lev (LevelTree.meet p.1 p.2))).card
        ≤ (V.image LevelTree.lev).card +
          ((V.product V).image (fun p : T × T =>
            LevelTree.lev (LevelTree.meet p.1 p.2))).card :=
            Finset.card_union_le _ _
    _ ≤ V.card + (V.product V).card :=
        Nat.add_le_add Finset.card_image_le Finset.card_image_le
    _ = V.card + V.card ^ 2 := by simp [pow_two]

theorem original_level_mem_budget (V : Finset T) {p : T}
    (hp : p ∈ V) :
    LevelTree.lev p ∈ poolMeetLevelBudget V := by
  classical
  unfold poolMeetLevelBudget
  exact Finset.mem_union.mpr (Or.inl
    (Finset.mem_image.mpr ⟨p, hp, rfl⟩))

theorem original_pair_meet_level_mem_budget (V : Finset T)
    {p q : T} (hp : p ∈ V) (hq : q ∈ V) :
    LevelTree.lev (LevelTree.meet p q) ∈ poolMeetLevelBudget V := by
  classical
  unfold poolMeetLevelBudget
  exact Finset.mem_union.mpr (Or.inr
    (Finset.mem_image.mpr
      ⟨(p, q), Finset.mem_product.mpr ⟨hp, hq⟩, rfl⟩))

/-- The actual Section 5 universal closure produces no nontrivial meet
level outside the finite quadratic budget, provided the chosen pool's
prefixes contain the input and are parameter-closed. -/
theorem closure_nontrivial_meet_level_mem_budget
    (S : STree T Label) (I : Set Nat) (X : Set T) (V : Finset T)
    (hX : X ⊆ prefixesOf (V : Set T))
    (hparam :
      SMTree.Envelope.ParameterClosedOver S (prefixesOf (V : Set T)) I)
    {a b : T}
    (ha : a ∈ SMTree.Envelope.closure S I X)
    (hb : b ∈ SMTree.Envelope.closure S I X)
    (hc : ∃ c : T, c ≤ a ∧ c ≤ b)
    (hleft : LevelTree.meet a b ≠ a)
    (hright : LevelTree.meet a b ≠ b) :
    LevelTree.lev (LevelTree.meet a b) ∈
      poolMeetLevelBudget V := by
  obtain ⟨p, hp, q, hq, _, heq⟩ :=
    closure_meet_has_originals S I X (V : Set T)
      hX hparam ha hb hc hleft hright
  have hpair := original_pair_meet_level_mem_budget V
    (Finset.mem_coe.mp hp) (Finset.mem_coe.mp hq)
  simpa only [heq] using hpair

/-- A conditional selected-level bound convenient for the final v10
induction. Once every selected level apart from zero is an original or
meet level, this gives an explicit N²+N+1 estimate without a sharp
2N tree-counting argument. -/
theorem selectedLevels_card_le_quadratic
    (V : Finset T) (selected : Finset Nat)
    (hselected : ∀ i ∈ selected,
      i = 0 ∨ i ∈ poolMeetLevelBudget V) :
    selected.card ≤ 1 + V.card + V.card ^ 2 := by
  classical
  let F := poolMeetLevelBudget V
  have hsub : selected ⊆ ({0} : Finset Nat) ∪ F := by
    intro i hi
    rcases hselected i hi with hzero | hmem
    · exact Finset.mem_union.mpr (Or.inl (by simpa [hzero]))
    · exact Finset.mem_union.mpr (Or.inr hmem)
  have hbudgetF : F.card ≤ V.card + V.card ^ 2 :=
    poolMeetLevelBudget_card_le V
  have hunion :=
    Finset.card_union_le ({0} : Finset Nat) F
  have hcard := Finset.card_le_card hsub
  calc
    selected.card ≤ (({0} : Finset Nat) ∪ F).card := hcard
    _ ≤ ({0} : Finset Nat).card + F.card := hunion
    _ ≤ 1 + V.card + V.card ^ 2 := by
      simp only [Finset.card_singleton]
      omega

end SuccessorTree.V10
