import SuccessorTree.V10.MeetProvenance
import Mathlib.Tactic

/-!
# Iterated prefix/meet closure over a pool of original types

The v10 bounded-envelope proof keeps a pool V containing its initial type
originals and the type vertices added by parameter closure. The elementary
invariant proved here is that **arbitrary iterated prefix and meet
operations** introduce no new representing originals, as long as every
parameter inserted later is already below a member of V.

The actual paper must still verify that its parameter-closure operation
has this property for V = {c} ∪ {i∈I : free_C(i)>0}.
-/

namespace SuccessorTree.V10

universe u
variable {T : Type u} [PartialOrder T] [LevelTree T]

/-- Iterated closure generated by originals, prescribed parameter nodes,
downward restriction, and componentwise meets. A parameter node is admitted
only from an explicitly specified set, not automatically. -/
inductive RepresentedClosure (V Parameters : Set T) : T → Prop where
  | original {v : T} (hv : v ∈ V) : RepresentedClosure V Parameters v
  | parameter {p : T} (hp : p ∈ Parameters) : RepresentedClosure V Parameters p
  | prefix {x y : T} (hy : RepresentedClosure V Parameters y)
      (hxy : x ≤ y) : RepresentedClosure V Parameters x
  | meet {x y : T}
      (hx : RepresentedClosure V Parameters x)
      (hy : RepresentedClosure V Parameters y)
      (hc : ∃ c : T, c ≤ x ∧ c ≤ y) :
      RepresentedClosure V Parameters (LevelTree.meet x y)

/-- Every generated node stays below some original in V. This handles
*any finite depth of iterated meets*, not just one round. -/
theorem representedClosure_subset_prefixesOf
    {V Parameters : Set T}
    (hparam : Parameters ⊆ prefixesOf V) :
    ∀ {x : T}, RepresentedClosure V Parameters x → x ∈ prefixesOf V := by
  intro x hx
  induction hx with
  | original hv =>
      exact ⟨_, hv, le_rfl⟩
  | parameter hp =>
      exact hparam hp
  | prefix _ hle ih =>
      obtain ⟨v, hv, hy⟩ := ih
      exact ⟨v, hv, hle.trans hy⟩
  | meet _ _ hc ihx ihy =>
      exact meet_mem_prefixesOf ihx ihy hc

/-- A nontrivial meet of any two nodes obtained by arbitrarily many
closure operations is already the meet of two members of V. -/
theorem generated_nontrivial_meet_has_originals
    {V Parameters : Set T}
    (hparam : Parameters ⊆ prefixesOf V)
    {s t : T}
    (hs : RepresentedClosure V Parameters s)
    (ht : RepresentedClosure V Parameters t)
    (hc : ∃ c : T, c ≤ s ∧ c ≤ t)
    (hleft : LevelTree.meet s t ≠ s)
    (hright : LevelTree.meet s t ≠ t) :
    ∃ a ∈ V, ∃ b ∈ V,
      (∃ c : T, c ≤ a ∧ c ≤ b) ∧
      LevelTree.meet s t = LevelTree.meet a b := by
  exact nontrivial_meet_has_originals
    (representedClosure_subset_prefixesOf hparam hs)
    (representedClosure_subset_prefixesOf hparam ht)
    hc hleft hright

end SuccessorTree.V10
