import SuccessorTree.V10.SocleBound
import Mathlib.Tactic

/-!
# The downward-generated auxiliary E relation in the v10 H construction

A real H-original is at position iota(j,m). Each admissible older pair
(iota(i,q),iota(j,m)) with i<j and q<m (or q=m=k) generates E
membership for *all* earlier coordinates t ≤ iota(i,q). The predicate
below is exactly this numerical closure scheme; it does not define the
entire relational H structure or assume the original manuscript's
one-way L-relation clause is an equivalence.

The formulas identify the first coordinate not generated by these E pairs.
Applying them to manuscript free_H requires proving that its E relation is
exactly the predicate generated here (and contains no other pairs).
-/

namespace SuccessorTree.V10

/-- Membership of a lower coordinate in the E-socle generated by all
admissible pairs with a fixed upper original \`iota(j,m)\`. -/
def generatedE (k j m t : Nat) : Prop :=
  ∃ i q : Nat,
    i < j ∧ q ≤ k ∧ (q < m ∨ (q = m ∧ m = k)) ∧
      t ≤ hPosition k i q

private theorem hPosition_mono
    (k i j q r : Nat) (hi : i ≤ j) (hq : q ≤ r) :
    hPosition k i q ≤ hPosition k j r := by
  calc
    hPosition k i q ≤ hPosition k j q := by
      unfold hPosition
      exact Nat.add_le_add_right
        (Nat.mul_le_mul_left (2 * (k + 1)) hi) (2 * q)
    _ ≤ hPosition k j r := by
      unfold hPosition
      exact Nat.add_le_add_left
        (Nat.mul_le_mul_left 2 hq) (2 * (k + 1) * j)

/-- Every generated E pair for a positive non-top original lies exactly
below its predicted free cut, and every earlier coordinate is generated. -/
theorem generatedE_nonTop_iff
    (k j m t : Nat)
    (hj : 0 < j) (hm : 0 < m) (hmk : m < k) :
    generatedE k j m t ↔ t < nonTopFreeCut k j m := by
  constructor
  · rintro ⟨i, q, hij, hqk, hallow, ht⟩
    have hij' : i ≤ j - 1 := by omega
    have hqm : q < m := by omega
    have hq' : q ≤ m - 1 := by omega
    have hbound :=
      hPosition_mono k i (j - 1) q (m - 1) hij' hq'
    dsimp [nonTopFreeCut]
    omega
  · intro ht
    refine ⟨j - 1, m - 1, by omega, by omega,
      Or.inl (by omega), ?_⟩
    dsimp [nonTopFreeCut] at ht
    omega

/-- The top-generation gate q=m=k permits the entire preceding top block
in E; this cut differs from that for non-top generations. -/
theorem generatedE_top_iff
    (k j t : Nat) (hj : 0 < j) (hk : 0 < k) :
    generatedE k j k t ↔
      t < hPosition k (j - 1) k + 1 := by
  constructor
  · rintro ⟨i, q, hij, hqk, _, ht⟩
    have hbound :=
      hPosition_mono k i (j - 1) q k (by omega) hqk
    omega
  · intro ht
    refine ⟨j - 1, k, by omega, le_rfl,
      Or.inr ⟨rfl, rfl⟩, ?_⟩
    omega

/-- Initial blocks and generation zero have no generated E pairs, for k>0. -/
theorem generatedE_empty_of_initial
    (k j m t : Nat) (hk : 0 < k)
    (hinitial : j = 0 ∨ m = 0) :
    ¬ generatedE k j m t := by
  rintro ⟨i, q, hij, _, hallow, _⟩
  rcases hinitial with hj | hm
  · omega
  · rcases hallow with h | ⟨h, heq⟩ <;> omega

/-- The predicted non-top free level really is the *first missing*
coordinate of the explicitly generated E relation. -/
theorem generatedE_nonTop_firstMissing
    (k j m : Nat) (hj : 0 < j) (hm : 0 < m) (hmk : m < k) :
    (∀ t < nonTopFreeCut k j m, generatedE k j m t) ∧
    ¬ generatedE k j m (nonTopFreeCut k j m) := by
  constructor
  · intro t ht
    exact (generatedE_nonTop_iff k j m t hj hm hmk).2 ht
  · intro ht
    exact (Nat.lt_irrefl _) ((generatedE_nonTop_iff
      k j m (nonTopFreeCut k j m) hj hm hmk).1 ht)

/-- The analogous first-missing statement for a positive top generation. -/
theorem generatedE_top_firstMissing
    (k j : Nat) (hj : 0 < j) (hk : 0 < k) :
    (∀ t < hPosition k (j - 1) k + 1, generatedE k j k t) ∧
    ¬ generatedE k j k (hPosition k (j - 1) k + 1) := by
  constructor
  · intro t ht
    exact (generatedE_top_iff k j t hj hk).2 ht
  · intro ht
    exact (Nat.lt_irrefl _) ((generatedE_top_iff
      k j (hPosition k (j - 1) k + 1) hj hk).1 ht)

/-- The auxiliary E-generation is downward closed in the lower coordinate:
the partite construction's E2 condition is automatic. -/
theorem generatedE_downward
    (k j m t u : Nat) (hu : u ≤ t)
    (ht : generatedE k j m t) : generatedE k j m u := by
  rcases ht with ⟨i, q, hij, hq, hallowed, hle⟩
  exact ⟨i, q, hij, hq, hallowed, hu.trans hle⟩

/-- Every generated E pair leaves at least one intervening coordinate.
In particular it respects the partial-structure spacing requirement. -/
theorem generatedE_gap
    (k j m t : Nat) (ht : generatedE k j m t) :
    t + 1 < hPosition k j m := by
  rcases ht with ⟨i, q, hij, hq, _hallowed, hle⟩
  have hlast : hPosition k i q ≤ hPosition k i k :=
    hPosition_mono k i i q k le_rfl hq
  have hnext :
      hPosition k i k + 2 = hPosition k (i + 1) 0 := by
    simp only [hPosition, Nat.mul_succ]
    ring
  have hblock : hPosition k (i + 1) 0 ≤ hPosition k j m :=
    hPosition_mono k (i + 1) j 0 m
      (Nat.succ_le_of_lt hij) (Nat.zero_le _)
  omega

/-- Any allowed copied pair is present in the downward-generated E socle.
For the manuscript H construction this is the E3/irreducibility linkage
once exact copying of binary relation tuples is proved. -/
theorem generatedE_of_allowedPair
    (k i j q m : Nat) (hij : i < j) (hq : q ≤ k)
    (hallowed : q < m ∨ (q = m ∧ m = k)) :
    generatedE k j m (hPosition k i q) :=
  ⟨i, q, hij, hq, hallowed, le_rfl⟩

/-- The first odd (fake) vertex belongs to the generated E-socle of a
later real top-generation vertex whenever k > 0. Thus an odd vertex is not
isolated in the full L+ structure: isolation holds only in the L-reduct. -/
theorem oddFake_not_E_isolated
    (k : Nat) (hk : 0 < k) :
    1 < hPosition k 1 k ∧ generatedE k 1 k 1 := by
  constructor
  · unfold hPosition
    omega
  · refine ⟨0, k, by omega, le_rfl, Or.inr ⟨rfl, rfl⟩, ?_⟩
    unfold hPosition
    omega

end SuccessorTree.V10
